'use strict'
function createRSpecTestFileString(emittedTest) {
  return `# Generated by Ruby template
${emittedTest.hooks.deps.join('\n')}

RSpec.describe 'Coverage Tests' do
  ${emittedTest.hooks.vars.join('\n  ')}
  before :example do
    ${emittedTest.hooks.beforeEach.join('\n    ')}
  end
  after :example do
    ${emittedTest.hooks.afterEach.join('\n    ')}
  end
  ${emittedTest.disabled ? 'skip' : 'it'} '${emittedTest.name}' do
    ${emittedTest.commands.join('\n    ')}
  end
end`
}

module.exports = createRSpecTestFileString
